### ISSUE TITLE
DOB is not working in Consultant page

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#94]
I am not able to add Date of birth in consultant page. The data selected in calendar is not being entered in textbox. 

![image](https://cloud.githubusercontent.com/assets/20394163/20474585/1bcdfcc6-afed-11e6-9d0d-76a57f7eabe5.png)

**Comment by NaziniSK** [comment]
Please provide browser details

**Comment by bhargavibindhu** [comment]
![image](https://cloud.githubusercontent.com/assets/20394163/20479031/a0cdbaf0-b002-11e6-977a-56ab90427f1e.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20479079/d3efe138-b002-11e6-8f6a-253b8d1a6318.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20479101/e701af22-b002-11e6-8168-0078a2be1432.png)


its working , same browser same version, please check

**Comment by NaziniSK** [comment]
1999-2016 age wont be 20 years , so it is not taking , please provide proper DOB

**Comment by bhargavibindhu** [comment]
its not taking any of the input. I am not specific about the 20years of difference instead whatever date is selected is not entered in the textbox.

**Comment by NaziniSK** [comment]
it will enter only above 20 years.  please  try 1995 and below years

**Comment by bhargavibindhu** [comment]
its not taking any of the input. I am not specific about the 20years of difference instead whatever date is selected is not entered in the textbox.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20479653/081dc716-b005-11e6-9170-6cac3bda5f15.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20479664/100b5bf0-b005-11e6-8c51-43d91db0bd6b.png)

this is not reproducing for me , only for 1997 and above it is not adding in input box, we are preventing it wantedly because of validations (checking whether date is above 20 years from current date , if true adding to input field (textbox) , if false showing message and not allowing in text box)
